name: NodeCI
on: push
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - uses: actions/setup-node@v2
                          with:
                                  node-version: 14.x
                        - run: make setup
                        - run: make start
                        - run: make test
                        - run: make lint
